### ISSUE TITLE
setParameters failed

### ISSUE THREAD

**Issue by robertoestivill** [kritts/HandWave#4]
I'm getting the following error when running any of the sample codes.
My device details is a Motorola Moto X 2nd gen (2014) running Android 5.1 stock.

```
D/AndroidRuntime(18022): Shutting down VM
E/AndroidRuntime(18022): FATAL EXCEPTION: main
E/AndroidRuntime(18022): Process: edu.washington.cs.gesturescrollertest, PID: 18022
E/AndroidRuntime(18022): java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.washington.cs.gesturescrollertest/edu.washington.cs.gesturescrollertest.MainActivity}: java.lang.RuntimeException: setParameters failed
E/AndroidRuntime(18022): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
E/AndroidRuntime(18022): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
E/AndroidRuntime(18022): 	at android.app.ActivityThread.access$800(ActivityThread.java:155)
E/AndroidRuntime(18022): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
E/AndroidRuntime(18022): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18022): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(18022): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(18022): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18022): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18022): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(18022): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(18022): Caused by: java.lang.RuntimeException: setParameters failed
E/AndroidRuntime(18022): 	at android.hardware.Camera.native_setParameters(Native Method)
E/AndroidRuntime(18022): 	at android.hardware.Camera.setParameters(Camera.java:1967)
E/AndroidRuntime(18022): 	at edu.washington.cs.touchfreelibrary.sensors.CameraGestureSensor.setCameraSettings(CameraGestureSensor.java:172)
E/AndroidRuntime(18022): 	at edu.washington.cs.touchfreelibrary.sensors.CameraGestureSensor.<init>(CameraGestureSensor.java:191)
E/AndroidRuntime(18022): 	at edu.washington.cs.gesturescrollertest.MainActivity.onCreate(MainActivity.java:50)
E/AndroidRuntime(18022): 	at android.app.Activity.performCreate(Activity.java:6010)
E/AndroidRuntime(18022): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
E/AndroidRuntime(18022): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
E/AndroidRuntime(18022): 	... 10 more
W/ActivityManager(  922):   Force finishing activity 1 edu.washington.cs.gesturescrollertest/.MainActivity
```

**Comment by johan-schoeman** [comment]
It is in all probability failing because of this call in class CameraGestureSensor (package edu.washington.cs.touchfreelibrary.sensors;):
params.set("iso", "400");

Some front facing cameras only support "iso" to be set to "auto":
params.set("iso", "auto");

Some device cameras expect for eg:
params.set("iso-speed", "auto");

You will have to change the code in the class and see what works for your device. See this posting:
http://stackoverflow.com/questions/2978095/android-camera-api-iso-setting
